const configuredContentUrl = import.meta.env?.VITE_SITE_CONTENT_URL;
const configuredDiagnosisUrl = import.meta.env?.VITE_DIAGNOSIS_URL;
const configuredQrCodeUrl = import.meta.env?.VITE_QR_CODE_URL;

export const DIAGNOSIS_URL = configuredDiagnosisUrl || "/diagnosis/?source=OFFICIAL_WEBSITE";

// Generated by the backend from PUBLIC_WEB_BASE_URL, not a static IP-address image.
export const QR_CODE_URL = configuredQrCodeUrl || "/api/public/channels/OFFICIAL_WEBSITE/qr";

export const siteConfig = Object.freeze({
  contentUrl: configuredContentUrl || "/data/site-content.json",
});
