"""Generate a structured Word archive for one customer lead."""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass
from datetime import datetime
from html.parser import HTMLParser
from io import BytesIO
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_ROW_HEIGHT_RULE, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor
from PIL import Image, ImageDraw, ImageFont

from app.models.lead import CompanyLead
from app.models.questionnaire import DiagnosisSubmission
from app.models.report import Report
from app.service.company_research import research_section_text, research_subsections
from app.service.report_content import build_report_presentation_html
from app.utils.time_utils import to_china_time, utc_now


FONT_NAME = "Microsoft YaHei"
NAVY = "17365D"
RED = "C00000"
DARK_RED = "A23A35"
BLUE = "2F5597"
PALE_RED = "FBE9E9"
PALE_GRAY = "F1F4F8"
RULE_GRAY = "D9E2F3"
PROGRESS_BLUE = "9CB7D6"
PROGRESS_GRAY = "E7ECF2"
BODY_COLOR = RGBColor(37, 37, 37)
MUTED_COLOR = RGBColor(102, 102, 102)
MISSING_RESEARCH = "暂未检索到可靠公开信息"
REPORT_CONTENT_WIDTH_CM = 17.4
SCORE_RATE_ABSOLUTE_TOLERANCE = 0.0001
DOCUMENT_STYLE_PRESET = "standard_business_brief"
CUSTOMER_COVER_OVERRIDE = "approved_reference_editorial_cover"
CUSTOMER_BODY_OVERRIDE = "reference_consulting_body_v2"
CUSTOMER_COVER_RULE_WIDTH_CM = 16.2
CUSTOMER_COVER_META_WIDTH_CM = 13.4
CUSTOMER_COVER_META_LABEL_WIDTH_CM = 3.0
CUSTOMER_COVER_META_VALUE_WIDTH_CM = 10.4
CUSTOMER_BODY_TEXT_SIZE_PT = 10.5
CUSTOMER_BODY_H1_SIZE_PT = 18.0
CUSTOMER_BODY_LEAD_SIZE_PT = 12.5
CUSTOMER_BODY_SUBHEAD_SIZE_PT = 11.5
CUSTOMER_BODY_LINE_SPACING = 1.35
CUSTOMER_BODY_PARAGRAPH_AFTER_PT = 6.0
CUSTOMER_BODY_HEADER_SIZE_PT = 7.5
CUSTOMER_BODY_FOOTER_SIZE_PT = 7.0
CUSTOMER_BODY_TABLE_SIZE_PT = 9.0

RESEARCH_SECTIONS: tuple[tuple[str, str, bool], ...] = (
    ("company_overview", "公司介绍", True),
    ("revenue_scale", "营收规模", True),
    ("products", "产品与服务", True),
    ("industry_characteristics", "行业特点", True),
    ("development_status", "发展现状", True),
    ("challenges", "可能遇到的挑战", False),
    ("ai_opportunities", "AI 能提供的帮助", False),
    ("analysis", "AI 综合分析", False),
)


class CustomerReportScoreError(ValueError):
    """Persisted score snapshot is unsafe for a formal customer deliverable."""


@dataclass(frozen=True, slots=True)
class CustomerReportScore:
    total_score: float
    max_score: float
    score_rate: float


class _HtmlNode:
    def __init__(self, tag: str, attrs: dict[str, str] | None = None) -> None:
        self.tag = tag
        self.attrs = attrs or {}
        self.children: list[_HtmlNode | str] = []


class _ReportHtmlParser(HTMLParser):
    """Build a small DOM for the controlled report HTML generated by this app."""

    _void_tags = {"br", "hr", "img", "meta", "link", "input"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = _HtmlNode("root")
        self.stack = [self.root]

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        node = _HtmlNode(tag.lower(), {key: value or "" for key, value in attrs})
        self.stack[-1].children.append(node)
        if tag.lower() not in self._void_tags:
            self.stack.append(node)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        for index in range(len(self.stack) - 1, 0, -1):
            if self.stack[index].tag == tag:
                del self.stack[index:]
                break

    def handle_data(self, data: str) -> None:
        if data:
            self.stack[-1].children.append(data)


def _set_run_font(run, size: float | None = None, bold: bool | None = None) -> None:
    run.font.name = FONT_NAME
    if size is not None:
        run.font.size = Pt(size)
    if bold is not None:
        run.bold = bold
    rpr = run._element.get_or_add_rPr()
    rfonts = rpr.rFonts
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.insert(0, rfonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        rfonts.set(qn(f"w:{attribute}"), FONT_NAME)


def _set_paragraph_font(paragraph, size: float = 10.5) -> None:
    for run in paragraph.runs:
        _set_run_font(run, size=size)


def _set_document_font(document: Document) -> None:
    for style in document.styles:
        if not getattr(style, "font", None):
            continue
        style.font.name = FONT_NAME
        style.font.color.rgb = BODY_COLOR
        rpr = style._element.get_or_add_rPr()
        rfonts = rpr.rFonts
        if rfonts is None:
            rfonts = OxmlElement("w:rFonts")
            rpr.insert(0, rfonts)
        for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
            rfonts.set(qn(f"w:{attribute}"), FONT_NAME)
    document.styles["Normal"].font.size = Pt(CUSTOMER_BODY_TEXT_SIZE_PT)
    document.styles["Normal"].paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
    document.styles["Normal"].paragraph_format.line_spacing = CUSTOMER_BODY_LINE_SPACING
    document.styles["Normal"].paragraph_format.space_after = Pt(CUSTOMER_BODY_PARAGRAPH_AFTER_PT)
    heading_1 = document.styles["Heading 1"]
    heading_1.font.size = Pt(CUSTOMER_BODY_H1_SIZE_PT)
    heading_1.font.bold = True
    heading_1.font.color.rgb = RGBColor.from_string(NAVY)
    heading_1.paragraph_format.space_before = Pt(17)
    heading_1.paragraph_format.space_after = Pt(7)
    heading_1.paragraph_format.line_spacing = 1.0
    heading_1.paragraph_format.keep_with_next = True
    heading_2 = document.styles["Heading 2"]
    heading_2.font.size = Pt(CUSTOMER_BODY_SUBHEAD_SIZE_PT)
    heading_2.font.bold = True
    heading_2.font.color.rgb = RGBColor.from_string(BLUE)
    heading_2.paragraph_format.space_before = Pt(9)
    heading_2.paragraph_format.space_after = Pt(5)
    heading_2.paragraph_format.line_spacing = 1.0
    heading_2.paragraph_format.keep_with_next = True


def _text(value: object | None, fallback: str = "未填写") -> str:
    if value is None or str(value).strip() == "":
        return fallback
    return str(value).strip()


def _format_datetime(value: datetime | None, fallback: str = "未记录") -> str:
    if value is None:
        return fallback
    return to_china_time(value).strftime("%Y-%m-%d %H:%M:%S")


def _shade(cell, color: str) -> None:
    properties = cell._tc.get_or_add_tcPr()
    shading = properties.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        properties.append(shading)
    shading.set(qn("w:fill"), color)


def _set_paragraph_border(
    paragraph,
    *,
    side: str = "bottom",
    color: str = RED,
    size: int = 8,
    space: int = 5,
) -> None:
    properties = paragraph._p.get_or_add_pPr()
    borders = properties.find(qn("w:pBdr"))
    if borders is None:
        borders = OxmlElement("w:pBdr")
        properties.append(borders)
    border = borders.find(qn(f"w:{side}"))
    if border is None:
        border = OxmlElement(f"w:{side}")
        borders.append(border)
    border.set(qn("w:val"), "single")
    border.set(qn("w:sz"), str(size))
    border.set(qn("w:space"), str(space))
    border.set(qn("w:color"), color)


def _set_paragraph_shading(paragraph, color: str) -> None:
    properties = paragraph._p.get_or_add_pPr()
    shading = properties.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        properties.append(shading)
    shading.set(qn("w:val"), "clear")
    shading.set(qn("w:color"), "auto")
    shading.set(qn("w:fill"), color)


def _set_table_borders(table, color: str = RULE_GRAY, size: int = 4) -> None:
    properties = table._tbl.tblPr
    borders = properties.find(qn("w:tblBorders"))
    if borders is None:
        borders = OxmlElement("w:tblBorders")
        properties.append(borders)
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        border = borders.find(qn(f"w:{side}"))
        if border is None:
            border = OxmlElement(f"w:{side}")
            borders.append(border)
        border.set(qn("w:val"), "single")
        border.set(qn("w:sz"), str(size))
        border.set(qn("w:color"), color)


def _remove_table_borders(table) -> None:
    properties = table._tbl.tblPr
    borders = properties.find(qn("w:tblBorders"))
    if borders is None:
        borders = OxmlElement("w:tblBorders")
        properties.append(borders)
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        border = borders.find(qn(f"w:{side}"))
        if border is None:
            border = OxmlElement(f"w:{side}")
            borders.append(border)
        border.set(qn("w:val"), "nil")
        border.set(qn("w:sz"), "0")
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), "auto")


def _set_cell_margins(cell, top: int = 90, start: int = 110, bottom: int = 90, end: int = 110) -> None:
    properties = cell._tc.get_or_add_tcPr()
    margins = properties.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        properties.append(margins)
    for side, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        element = margins.find(qn(f"w:{side}"))
        if element is None:
            element = OxmlElement(f"w:{side}")
            margins.append(element)
        element.set(qn("w:w"), str(value))
        element.set(qn("w:type"), "dxa")


def _prevent_row_split(row) -> None:
    properties = row._tr.get_or_add_trPr()
    if properties.find(qn("w:cantSplit")) is None:
        properties.append(OxmlElement("w:cantSplit"))


def _repeat_table_header(row) -> None:
    properties = row._tr.get_or_add_trPr()
    if properties.find(qn("w:tblHeader")) is None:
        properties.append(OxmlElement("w:tblHeader"))


def _keep_row_with_next(row) -> None:
    """Avoid leaving a repeated table header alone at the bottom of a page."""
    for cell in row.cells:
        for paragraph in cell.paragraphs:
            paragraph.paragraph_format.keep_with_next = True


def _set_fixed_table_layout(table) -> None:
    properties = table._tbl.tblPr
    layout = properties.find(qn("w:tblLayout"))
    if layout is None:
        layout = OxmlElement("w:tblLayout")
        properties.append(layout)
    layout.set(qn("w:type"), "fixed")


def _set_table_width(table, width_cm: float, *, indent_twips: int = 0) -> None:
    properties = table._tbl.tblPr
    width = properties.find(qn("w:tblW"))
    if width is None:
        width = OxmlElement("w:tblW")
        properties.append(width)
    width.set(qn("w:w"), str(Cm(width_cm).twips))
    width.set(qn("w:type"), "dxa")
    indent = properties.find(qn("w:tblInd"))
    if indent is None:
        indent = OxmlElement("w:tblInd")
        properties.append(indent)
    indent.set(qn("w:w"), str(indent_twips))
    indent.set(qn("w:type"), "dxa")


def _set_table_grid_widths(table, widths_cm: list[float]) -> None:
    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width_cm in widths_cm:
        column = OxmlElement("w:gridCol")
        column.set(qn("w:w"), str(Cm(width_cm).twips))
        grid.append(column)


def _set_cell_width(cell, width_cm: float) -> None:
    cell.width = Cm(width_cm)
    properties = cell._tc.get_or_add_tcPr()
    width = properties.find(qn("w:tcW"))
    if width is None:
        width = OxmlElement("w:tcW")
        properties.append(width)
    width.set(qn("w:w"), str(Cm(width_cm).twips))
    width.set(qn("w:type"), "dxa")


def _set_cell_text(cell, label: str, value: str) -> None:
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
    _shade(cell, PALE_GRAY)
    _set_cell_margins(cell)
    paragraph = cell.paragraphs[0]
    paragraph.paragraph_format.space_after = Pt(0)
    label_run = paragraph.add_run(f"{label}\n")
    label_run.font.color.rgb = MUTED_COLOR
    _set_run_font(label_run, size=8.5, bold=True)
    value_run = paragraph.add_run(value)
    value_run.font.color.rgb = BODY_COLOR
    _set_run_font(value_run, size=10.5, bold=True)


def _set_score_cell(cell, label: str, value: str) -> None:
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
    _shade(cell, "F6F8FB")
    _set_cell_margins(cell, top=90, start=90, bottom=90, end=90)
    paragraph = cell.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(0)
    paragraph.paragraph_format.line_spacing = 1.0
    label_run = paragraph.add_run(f"{label}  ")
    label_run.font.color.rgb = MUTED_COLOR
    _set_run_font(label_run, size=9, bold=False)
    value_run = paragraph.add_run(value)
    value_run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(value_run, size=13, bold=True)


def _add_part_title(document: Document, number: str, title: str, subtitle: str | None = None) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(7)
    paragraph.paragraph_format.keep_with_next = True
    title_run = paragraph.add_run(f"{number}{title}")
    title_run.font.color.rgb = RGBColor(18, 46, 77)
    _set_run_font(title_run, size=19, bold=True)
    if subtitle:
        note = document.add_paragraph(subtitle)
        note.paragraph_format.space_after = Pt(14)
        for run in note.runs:
            run.font.color.rgb = MUTED_COLOR
            _set_run_font(run, size=9.5)


def _add_section_title(document: Document, number: int | str, title: str) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(13)
    paragraph.paragraph_format.space_after = Pt(6)
    paragraph.paragraph_format.keep_with_next = True
    run = paragraph.add_run(f"{number}. {title}")
    run.font.color.rgb = RGBColor(20, 76, 112)
    _set_run_font(run, size=13, bold=True)


def _add_page_number(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = " PAGE "
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend([begin, instruction, end])
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=CUSTOMER_BODY_FOOTER_SIZE_PT)


def _configure_section(
    section,
    header_text: str = "AI 原生企业转型诊断档案",
    *,
    footer_date: str | None = None,
) -> None:
    section.page_width = Cm(21.0)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(1.8)
    section.bottom_margin = Cm(1.7)
    section.left_margin = Cm(1.8)
    section.right_margin = Cm(1.8)
    section.header_distance = Cm(0.7)
    section.footer_distance = Cm(0.7)
    header = section.header.paragraphs[0]
    header.text = header_text
    header.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _set_paragraph_border(header, side="bottom", size=6, space=4)
    for run in header.runs:
        run.font.color.rgb = MUTED_COLOR
        _set_run_font(run, size=CUSTOMER_BODY_HEADER_SIZE_PT, bold=False)

    footer = section.footer
    footer.paragraphs[0].text = ""
    footer_table = footer.add_table(rows=1, cols=3, width=Cm(REPORT_CONTENT_WIDTH_CM))
    footer_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    footer_table.autofit = False
    _set_fixed_table_layout(footer_table)
    _set_table_width(footer_table, REPORT_CONTENT_WIDTH_CM)
    footer_widths = [REPORT_CONTENT_WIDTH_CM / 3] * 3
    _set_table_grid_widths(footer_table, footer_widths)
    _remove_table_borders(footer_table)
    footer_cells = footer_table.rows[0].cells
    for cell, width in zip(footer_cells, footer_widths):
        _set_cell_width(cell, width)
        _set_cell_margins(cell, top=0, start=0, bottom=0, end=0)
    label = "企业 AI 转型诊断"
    if footer_date:
        label = f"{label} | {footer_date}"
    left = footer_cells[0].paragraphs[0]
    left.alignment = WD_ALIGN_PARAGRAPH.LEFT
    left.paragraph_format.space_after = Pt(0)
    left_run = left.add_run(label)
    left_run.font.color.rgb = MUTED_COLOR
    _set_run_font(left_run, size=CUSTOMER_BODY_FOOTER_SIZE_PT)
    center = footer_cells[1].paragraphs[0]
    center.paragraph_format.space_after = Pt(0)
    _add_page_number(center)


def _add_cover(document: Document, company_name: str) -> None:
    for _ in range(5):
        document.add_paragraph()
    eyebrow = document.add_paragraph()
    eyebrow.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = eyebrow.add_run(company_name)
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=11, bold=True)
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_before = Pt(10)
    title.paragraph_format.space_after = Pt(16)
    run = title.add_run("AI 转型诊断完整档案")
    run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(run, size=26, bold=True)
    subject = document.add_paragraph()
    subject.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subject.add_run("从诊断共识走向可执行的 AI 转型路径")
    run.font.color.rgb = RGBColor.from_string(RED)
    _set_run_font(run, size=13, bold=True)
    rule = document.add_paragraph()
    rule.paragraph_format.space_before = Pt(20)
    rule.paragraph_format.space_after = Pt(14)
    _set_paragraph_border(rule, side="bottom", size=7, space=0)
    generated = document.add_paragraph()
    generated.alignment = WD_ALIGN_PARAGRAPH.CENTER
    generated.paragraph_format.space_before = Pt(34)
    run = generated.add_run(f"导出时间：{_format_datetime(utc_now())}（北京时间）")
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=9.5)
    confidentiality = document.add_paragraph()
    confidentiality.alignment = WD_ALIGN_PARAGRAPH.CENTER
    confidentiality.paragraph_format.space_before = Pt(100)
    run = confidentiality.add_run("内部资料 · 请妥善保管")
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=9)


def _new_part(document: Document, number: str, title: str, subtitle: str | None = None) -> None:
    document.add_page_break()
    _add_part_title(document, number, title, subtitle)


def _load_research(report: Report | None) -> dict:
    if not report or not report.company_research_json:
        return {}
    try:
        value = json.loads(report.company_research_json)
        return value if isinstance(value, dict) else {}
    except (TypeError, json.JSONDecodeError):
        return {}


def _source_reference_text(research: dict, key: str, source_count: int) -> str:
    references = research.get("source_refs") or {}
    values = references.get(key) if isinstance(references, dict) else None
    if isinstance(values, list):
        indexes = [int(value) for value in values if str(value).isdigit() and 1 <= int(value) <= source_count]
        if indexes:
            return "资料来源：" + " ".join(f"[来源{index}]" for index in dict.fromkeys(indexes))
    if research.get(key) == MISSING_RESEARCH:
        return "资料来源：暂未检索到可靠公开信息"
    return "资料来源：证据校验失败，未找到可核验来源编号"


def _add_research_section(document: Document, research: dict) -> None:
    sources = [item for item in (research.get("sources") or []) if isinstance(item, dict)]
    for index, (key, title, factual) in enumerate(RESEARCH_SECTIONS, start=1):
        _add_section_title(document, index, title)
        value = research.get(key)
        subsections = research_subsections(value)
        if subsections:
            for subsection in subsections:
                heading = document.add_paragraph()
                heading.paragraph_format.space_before = Pt(2)
                heading.paragraph_format.space_after = Pt(2)
                run = heading.add_run(subsection["title"])
                run.bold = True
                run.font.color.rgb = RGBColor.from_string(NAVY)
                _set_run_font(run, size=10.5)
                paragraph = document.add_paragraph(subsection["content"])
                paragraph.paragraph_format.line_spacing = 1.35
                paragraph.paragraph_format.space_after = Pt(5)
                _set_paragraph_font(paragraph)
        else:
            content = research_section_text(value) or MISSING_RESEARCH
            paragraph = document.add_paragraph(content)
            paragraph.paragraph_format.line_spacing = 1.35
            paragraph.paragraph_format.space_after = Pt(5)
            _set_paragraph_font(paragraph)
        if factual:
            source_note = document.add_paragraph(_source_reference_text(research, key, len(sources)))
            source_note.paragraph_format.space_after = Pt(8)
            for run in source_note.runs:
                run.font.color.rgb = MUTED_COLOR
                _set_run_font(run, size=8.5)
        else:
            analysis_note = document.add_paragraph("性质说明：结合公开信息形成的 AI 分析判断，不作为已核实事实。")
            analysis_note.paragraph_format.space_after = Pt(8)
            for run in analysis_note.runs:
                run.font.color.rgb = MUTED_COLOR
                _set_run_font(run, size=8.5)

    _add_section_title(document, 9, "信息来源")
    researched_at = _text(research.get("researched_at"), "未记录")
    note = document.add_paragraph(f"检索时间：{researched_at}")
    for run in note.runs:
        run.font.color.rgb = MUTED_COLOR
        _set_run_font(run, size=8.5)
    if not sources:
        paragraph = document.add_paragraph(MISSING_RESEARCH)
        _set_paragraph_font(paragraph)
        return
    table = document.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    headers = ("编号", "来源", "网址")
    for cell, header in zip(table.rows[0].cells, headers):
        _shade(cell, NAVY)
        cell.text = header
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in paragraph.runs:
                run.font.color.rgb = RGBColor(255, 255, 255)
                _set_run_font(run, size=9, bold=True)
    for index, source in enumerate(sources, start=1):
        cells = table.add_row().cells
        values = (f"来源{index}", _text(source.get("title"), "未命名来源"), _text(source.get("url"), "未提供网址"))
        for cell, value in zip(cells, values):
            _set_cell_margins(cell)
            cell.text = value
            for paragraph in cell.paragraphs:
                _set_paragraph_font(paragraph, size=8.5)
        if index % 2 == 0:
            for cell in cells:
                _shade(cell, PALE_GRAY)
        _prevent_row_split(table.rows[-1])


def _node_text(node: _HtmlNode | str) -> str:
    if isinstance(node, str):
        return node
    if node.tag == "br":
        return "\n"
    return "".join(_node_text(child) for child in node.children)


def _normalized_node_text(node: _HtmlNode | str) -> str:
    value = _node_text(node).replace("\xa0", " ")
    lines = [re.sub(r"[ \t]+", " ", line).strip() for line in value.splitlines()]
    return "\n".join(line for line in lines if line).strip()


def _load_report_dimensions(report: Report | None) -> list[dict]:
    if not report or not getattr(report, "summary_json", None):
        return []
    try:
        payload = json.loads(report.summary_json)
    except (TypeError, json.JSONDecodeError):
        return []
    dimensions = payload.get("dimensions") if isinstance(payload, dict) else None
    if not isinstance(dimensions, list):
        return []
    return [item for item in dimensions if isinstance(item, dict) and item.get("module_name")]


def _chart_font(size: int, *, bold: bool = False):
    candidates = (
        Path("C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJKsc-Bold.otf" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJKsc-Regular.otf"),
        Path("/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"),
    )
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size=size)
    return ImageFont.load_default()


def _dimension_rate(dimension: dict) -> float:
    try:
        return max(0.0, min(1.0, float(dimension.get("score_rate") or 0)))
    except (TypeError, ValueError):
        return 0.0


def _fit_label(draw: ImageDraw.ImageDraw, value: str, font, max_width: int) -> str:
    if draw.textbbox((0, 0), value, font=font)[2] <= max_width:
        return value
    suffix = "..."
    trimmed = value
    while trimmed and draw.textbbox((0, 0), trimmed + suffix, font=font)[2] > max_width:
        trimmed = trimmed[:-1]
    return trimmed + suffix


def _chart_dimension_label(dimension: dict) -> str:
    """Return a concise chart-only label without changing the report snapshot."""
    label = str(dimension.get("module_name") or "").strip()
    module_code = str(dimension.get("module_code") or "").strip().upper()
    if module_code == "M01" and "用户/客户" in label and "中心" in label:
        return "用户/客户中心"
    return label


def _draw_chart_heading(draw: ImageDraw.ImageDraw, title: str, subtitle: str) -> None:
    draw.text((46, 28), title, fill=f"#{BLUE}", font=_chart_font(31, bold=True))
    draw.text((46, 74), subtitle, fill="#666666", font=_chart_font(20))
    draw.line((46, 108, 1354, 108), fill=f"#{RULE_GRAY}", width=2)


def _build_ranking_chart(dimensions: list[dict]) -> BytesIO:
    ordered = sorted(dimensions, key=_dimension_rate)
    row_height = 54
    height = max(410, 160 + len(ordered) * row_height)
    image = Image.new("RGB", (1400, height), "white")
    draw = ImageDraw.Draw(image)
    _draw_chart_heading(draw, "能力成熟度排行", "当前启用维度得分率从低到高排列，快速定位优先改善环节")
    left, right, top = 370, 1320, 140
    chart_width = right - left
    label_font = _chart_font(23)
    value_font = _chart_font(21, bold=True)
    for tick in range(0, 101, 25):
        x = left + chart_width * tick / 100
        draw.line((x, top, x, height - 55), fill="#E2E8F0", width=2)
        label = f"{tick}%"
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((x - (box[2] - box[0]) / 2, height - 44), label, fill="#8A98AA", font=label_font)
    for index, dimension in enumerate(ordered):
        rate = _dimension_rate(dimension)
        y = top + index * row_height + 8
        label = _fit_label(draw, _chart_dimension_label(dimension), label_font, 285)
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((left - 28 - (box[2] - box[0]), y + 4), label, fill="#58677D", font=label_font)
        bar_width = max(4, int(chart_width * rate))
        fill = f"#{PALE_RED}" if rate < 0.5 else "#DDE6F1"
        outline = f"#{RED}" if rate < 0.5 else f"#{NAVY}"
        draw.rectangle((left, y, left + bar_width, y + 30), fill=fill, outline=outline, width=3)
        draw.text((min(left + bar_width + 14, right - 58), y + 2), f"{round(rate * 100)}%", fill="#34445B", font=value_font)
    output = BytesIO()
    image.save(output, format="PNG", optimize=True)
    output.seek(0)
    return output


def _build_radar_chart(dimensions: list[dict]) -> BytesIO:
    count = len(dimensions)
    size = 1040
    image = Image.new("RGB", (1400, size), "white")
    draw = ImageDraw.Draw(image)
    _draw_chart_heading(draw, "AI 转型能力雷达图", "面积越大代表各项能力越均衡，红色节点标记得分率低于 50% 的维度")
    center_x, center_y = 700, 565
    radius = 330
    angles = [(-math.pi / 2) + 2 * math.pi * index / count for index in range(count)]
    for level in (0.25, 0.5, 0.75, 1.0):
        points = [(center_x + radius * level * math.cos(angle), center_y + radius * level * math.sin(angle)) for angle in angles]
        draw.polygon(points, outline="#D9E3EF", width=2)
    for angle in angles:
        draw.line((center_x, center_y, center_x + radius * math.cos(angle), center_y + radius * math.sin(angle)), fill="#D9E3EF", width=2)
    values = [_dimension_rate(dimension) for dimension in dimensions]
    points = [(center_x + radius * rate * math.cos(angle), center_y + radius * rate * math.sin(angle)) for rate, angle in zip(values, angles)]
    overlay = Image.new("RGBA", image.size, (255, 255, 255, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    overlay_draw.polygon(points, fill=(23, 54, 93, 45), outline=f"#{NAVY}", width=6)
    image = Image.alpha_composite(image.convert("RGBA"), overlay)
    draw = ImageDraw.Draw(image)
    for (x, y), rate in zip(points, values):
        color = f"#{RED}" if rate < 0.5 else f"#{NAVY}"
        draw.ellipse((x - 11, y - 11, x + 11, y + 11), fill=color, outline="white", width=4)
    label_font = _chart_font(23)
    for dimension, angle in zip(dimensions, angles):
        label = _fit_label(draw, _chart_dimension_label(dimension), label_font, 250)
        label_radius = radius + 74
        x = center_x + label_radius * math.cos(angle)
        y = center_y + label_radius * math.sin(angle)
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((x - (box[2] - box[0]) / 2, y - (box[3] - box[1]) / 2), label, fill="#47566D", font=label_font)
    output = BytesIO()
    image.convert("RGB").save(output, format="PNG", optimize=True)
    output.seek(0)
    return output


def _add_maturity_charts(document: Document, dimensions: list[dict]) -> None:
    if len(dimensions) < 3:
        return
    for chart in (_build_ranking_chart(dimensions), _build_radar_chart(dimensions)):
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.paragraph_format.space_before = Pt(4)
        paragraph.paragraph_format.space_after = Pt(10)
        paragraph.add_run().add_picture(chart, width=Cm(16.2))


def _add_inline_runs(paragraph, node: _HtmlNode | str, bold: bool = False) -> None:
    if isinstance(node, str):
        text = re.sub(r"[ \t\r\n]+", " ", node)
        if text:
            run = paragraph.add_run(text)
            _set_run_font(run, size=CUSTOMER_BODY_TEXT_SIZE_PT, bold=bold)
            if bold:
                run.font.color.rgb = RGBColor.from_string(NAVY)
        return
    if node.tag == "br":
        paragraph.add_run().add_break()
        return
    next_bold = bold or node.tag in {"strong", "b"}
    for child in node.children:
        _add_inline_runs(paragraph, child, next_bold)


def _find_descendants(node: _HtmlNode, tags: set[str]) -> list[_HtmlNode]:
    found: list[_HtmlNode] = []
    for child in node.children:
        if not isinstance(child, _HtmlNode):
            continue
        if child.tag in tags:
            found.append(child)
        else:
            found.extend(_find_descendants(child, tags))
    return found


def _add_report_table(document: Document, node: _HtmlNode) -> None:
    rows = _find_descendants(node, {"tr"})
    parsed_rows: list[tuple[list[str], bool]] = []
    for row in rows:
        cells = [child for child in row.children if isinstance(child, _HtmlNode) and child.tag in {"th", "td"}]
        if not cells:
            cells = _find_descendants(row, {"th", "td"})
        if cells:
            parsed_rows.append(([_normalized_node_text(cell) for cell in cells], any(cell.tag == "th" for cell in cells)))
    if not parsed_rows:
        return
    column_count = max(len(row) for row, _ in parsed_rows)
    table = document.add_table(rows=0, cols=column_count)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    _set_fixed_table_layout(table)
    _set_table_borders(table)
    classes = set(node.attrs.get("class", "").split())
    is_summary_table = "report-finding-table" in classes and not classes.intersection(
        {"report-cad-table", "report-contradiction-table", "report-workshop-table"}
    )
    if "report-workshop-table" in classes and column_count == 5:
        ratios = (0.09, 0.20, 0.29, 0.28, 0.14)
    elif "report-cad-table" in classes and column_count == 3:
        ratios = (0.12, 0.40, 0.48)
    elif "report-contradiction-table" in classes and column_count == 3:
        ratios = (0.25, 0.45, 0.30)
    elif is_summary_table and column_count == 3:
        ratios = (0.07, 0.30, 0.63)
    else:
        ratios = tuple(1 / column_count for _ in range(column_count))
    widths = [REPORT_CONTENT_WIDTH_CM * ratio for ratio in ratios]
    _set_table_grid_widths(table, widths)
    for row_index, (values, is_header) in enumerate(parsed_rows):
        cells = table.add_row().cells
        for cell_index, cell in enumerate(cells):
            value = values[cell_index] if cell_index < len(values) else ""
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
            _set_cell_width(cell, widths[cell_index])
            horizontal_margin = 35 if is_summary_table and cell_index == 0 else 100
            _set_cell_margins(cell, top=78, start=horizontal_margin, bottom=78, end=horizontal_margin)
            cell.text = value
            if is_header:
                _shade(cell, NAVY)
            elif row_index % 2 == 0:
                _shade(cell, PALE_GRAY)
            for paragraph in cell.paragraphs:
                paragraph.paragraph_format.space_after = Pt(0)
                paragraph.paragraph_format.line_spacing = 1.15
                if cell_index == 0 and is_summary_table:
                    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in paragraph.runs:
                    if is_header:
                        run.font.color.rgb = RGBColor(255, 255, 255)
                    elif is_summary_table and cell_index == 1:
                        run.font.color.rgb = RGBColor.from_string(RED)
                    else:
                        run.font.color.rgb = BODY_COLOR
                    font_size = (
                        8.5
                        if column_count >= 4 or (is_summary_table and cell_index == 0)
                        else CUSTOMER_BODY_TABLE_SIZE_PT
                    )
                    _set_run_font(run, size=font_size, bold=is_header or (cell_index == 1 and is_summary_table))
        if is_header:
            _repeat_table_header(table.rows[-1])
            _keep_row_with_next(table.rows[-1])
            _prevent_row_split(table.rows[-1])
    if "report-cad-table" in classes and len(table.rows) > 2:
        core_conclusion = parsed_rows[1][0][0] if parsed_rows[1][0] else ""
        merged_cell = table.cell(1, 0).merge(table.cell(len(table.rows) - 1, 0))
        merged_cell.text = core_conclusion
        merged_cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        _set_cell_margins(merged_cell, top=110, start=110, bottom=110, end=110)
        for paragraph in merged_cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            paragraph.paragraph_format.space_after = Pt(0)
            paragraph.paragraph_format.line_spacing = 1.2
            for run in paragraph.runs:
                run.font.color.rgb = BODY_COLOR
                _set_run_font(run, size=9, bold=True)
    document.add_paragraph().paragraph_format.space_after = Pt(0)


def _add_report_callout(document: Document, node: _HtmlNode) -> None:
    classes = set(node.attrs.get("class", "").split())
    is_contact = "report-contact-callout" in classes
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.left_indent = Cm(0.28)
    paragraph.paragraph_format.right_indent = Cm(0.18)
    paragraph.paragraph_format.space_before = Pt(14 if is_contact else 7)
    paragraph.paragraph_format.space_after = Pt(4 if is_contact else 10)
    paragraph.paragraph_format.line_spacing = 1.35 if is_contact else 1.3
    paragraph.paragraph_format.keep_together = True
    _set_paragraph_shading(paragraph, PALE_RED)
    _set_paragraph_border(paragraph, side="left", color=RED, size=18, space=5)
    if is_contact:
        lines = [_normalized_node_text(item) for item in _find_descendants(node, {"p"})]
        for index, line in enumerate(value for value in lines if value):
            if index:
                paragraph.add_run().add_break()
            run = paragraph.add_run(line)
            run.font.color.rgb = RGBColor.from_string(NAVY)
            _set_run_font(run, size=10, bold=True)
    else:
        run = paragraph.add_run(_normalized_node_text(node))
        run.font.color.rgb = RGBColor.from_string(NAVY)
        _set_run_font(run, size=CUSTOMER_BODY_TEXT_SIZE_PT, bold=True)


def _render_report_nodes(
    document: Document,
    nodes: Iterable[_HtmlNode | str],
    dimensions: list[dict] | None = None,
    chart_state: dict[str, bool] | None = None,
) -> None:
    chart_state = chart_state if chart_state is not None else {"inserted": False}
    for node in nodes:
        if isinstance(node, str):
            if node.strip():
                paragraph = document.add_paragraph(node.strip())
                _set_paragraph_font(paragraph)
            continue
        classes = set(node.attrs.get("class", "").split())
        if "report-diagnosis-callout" in classes:
            _add_report_callout(document, node)
        elif node.tag == "h2":
            heading_text = _normalized_node_text(node)
            paragraph = document.add_paragraph(style="Heading 1")
            run = paragraph.add_run(heading_text)
            run.font.color.rgb = RGBColor.from_string(NAVY)
            _set_run_font(run, size=CUSTOMER_BODY_H1_SIZE_PT, bold=True)
            if heading_text.startswith("二、能力成熟度") and dimensions and not chart_state["inserted"]:
                _add_maturity_charts(document, dimensions)
                chart_state["inserted"] = True
        elif node.tag in {"h3", "h4"} or "report-module-head" in classes:
            paragraph = document.add_paragraph(style="Heading 2")
            run = paragraph.add_run(_normalized_node_text(node))
            run.font.color.rgb = RGBColor.from_string(BLUE)
            _set_run_font(run, size=CUSTOMER_BODY_SUBHEAD_SIZE_PT, bold=True)
        elif node.tag == "p" or "report-module-body" in classes:
            paragraph = document.add_paragraph()
            is_lead = "report-lead" in classes
            is_accent = bool(
                classes.intersection({"report-module-judgment", "report-section-note--accent"})
                or "report-section-note" in classes
            )
            paragraph.paragraph_format.line_spacing = 1.25 if is_lead else CUSTOMER_BODY_LINE_SPACING
            paragraph.paragraph_format.space_after = Pt(
                7 if is_lead else 5 if is_accent else CUSTOMER_BODY_PARAGRAPH_AFTER_PT
            )
            if is_lead or is_accent:
                paragraph.paragraph_format.keep_with_next = True
            for child in node.children:
                _add_inline_runs(paragraph, child)
            if is_lead:
                for run in paragraph.runs:
                    run.font.color.rgb = RGBColor.from_string(RED)
                    _set_run_font(run, size=CUSTOMER_BODY_LEAD_SIZE_PT, bold=True)
            elif is_accent:
                paragraph.paragraph_format.space_before = Pt(1)
                paragraph.paragraph_format.line_spacing = 1.1
                for run in paragraph.runs:
                    run.font.color.rgb = RGBColor.from_string(DARK_RED)
                    _set_run_font(run, size=9.5, bold=False)
        elif node.tag == "table":
            _add_report_table(document, node)
        elif node.tag in {"ol", "ul"}:
            list_style = "List Number" if node.tag == "ol" else "List Bullet"
            for item in [child for child in node.children if isinstance(child, _HtmlNode) and child.tag == "li"]:
                paragraph = document.add_paragraph(style=list_style)
                paragraph.paragraph_format.space_after = Pt(CUSTOMER_BODY_PARAGRAPH_AFTER_PT)
                paragraph.paragraph_format.line_spacing = CUSTOMER_BODY_LINE_SPACING
                for child in item.children:
                    _add_inline_runs(paragraph, child)
        elif node.tag in {"article", "section", "div", "main", "body", "root"}:
            _render_report_nodes(document, node.children, dimensions, chart_state)


def build_final_diagnosis_report(document: Document, report: Report) -> None:
    """把最终诊断报告渲染进现有文档，内部 Word 档案第三部分与客户 DOCX 共用。

    两份文档由此共享同一套标题样式、深蓝表头、表格列宽、行距、字号、
    成熟度排行图与雷达图；调整这里即可让两边同步变化。
    """
    parser = _ReportHtmlParser()
    parser.feed(build_report_presentation_html(report.html_content, report.summary_json))
    _render_report_nodes(document, parser.root.children, _load_report_dimensions(report))


def _add_final_report(document: Document, report: Report | None, final_report_sent: bool) -> None:
    if not report or not final_report_sent or not report.html_content:
        paragraph = document.add_paragraph("客户最终诊断报告尚未发送，暂无可导出的最终版本。")
        paragraph.paragraph_format.space_before = Pt(12)
        _set_paragraph_font(paragraph)
        return
    build_final_diagnosis_report(document, report)


def _numeric_score_value(score: dict, key: str) -> float:
    value = score.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise CustomerReportScoreError(f"score.{key} 必须是非布尔数值")
    numeric = float(value)
    if not math.isfinite(numeric):
        raise CustomerReportScoreError(f"score.{key} 必须是有限数值")
    return numeric


def customer_report_score(report: Report) -> CustomerReportScore:
    """Load and strictly validate the persisted score snapshot used in delivery.

    ``summary_json.score.total`` is the persisted total-score field produced by
    the report generator. Validation happens before either PDF renderer and is
    also enforced by the standalone customer-DOCX builder, so formal output can
    never replace an invalid score with a visual dash.
    """
    raw_summary = getattr(report, "summary_json", None)
    if not raw_summary:
        raise CustomerReportScoreError("summary_json 缺少 score 评分快照")
    try:
        payload = json.loads(raw_summary)
    except (TypeError, json.JSONDecodeError) as exc:
        raise CustomerReportScoreError("summary_json 不是有效 JSON") from exc
    score = payload.get("score") if isinstance(payload, dict) else None
    if not isinstance(score, dict):
        raise CustomerReportScoreError("summary_json 缺少 score 评分对象")

    total_score = _numeric_score_value(score, "total")
    max_score = _numeric_score_value(score, "max_score")
    score_rate = _numeric_score_value(score, "score_rate")
    if total_score < 0:
        raise CustomerReportScoreError("score.total_score 不得小于 0")
    if max_score <= 0:
        raise CustomerReportScoreError("score.max_score 必须大于 0")
    if total_score > max_score:
        raise CustomerReportScoreError("score.total_score 不得大于 score.max_score")
    if not 0 <= score_rate <= 1:
        raise CustomerReportScoreError("score.score_rate 必须位于 0 到 1 之间")
    expected_rate = total_score / max_score
    if not math.isclose(
        score_rate,
        expected_rate,
        rel_tol=0.0,
        abs_tol=SCORE_RATE_ABSOLUTE_TOLERANCE,
    ):
        raise CustomerReportScoreError(
            "score.score_rate 与 score.total_score / score.max_score 不一致"
        )
    return CustomerReportScore(
        total_score=total_score,
        max_score=max_score,
        score_rate=score_rate,
    )


def _report_number(report: Report) -> str:
    report_id = getattr(report, "id", None)
    return f"RPT-{report_id:06d}" if isinstance(report_id, int) else "RPT-UNKNOWN"


def _report_date(report: Report) -> str:
    created = getattr(report, "created_at", None)
    if not created:
        return "未记录"
    local_date = to_china_time(created)
    return f"{local_date.year} 年 {local_date.month} 月 {local_date.day} 日"


def _score_number_text(value: float) -> str:
    return str(int(value)) if value.is_integer() else f"{value:g}"


def _score_rate_text(score: CustomerReportScore) -> str:
    return f"{round(score.score_rate * 100)}%"


def _short_company_name(company_name: str) -> str:
    normalized = company_name.strip() or "企业"
    for suffix in (
        "集团股份有限公司",
        "集团有限责任公司",
        "股份有限公司",
        "有限责任公司",
        "集团有限公司",
        "有限公司",
    ):
        if normalized.endswith(suffix) and len(normalized) > len(suffix):
            return normalized[: -len(suffix)].strip()
    return normalized


def _cover_title_size(company_name: str) -> float:
    """Keep unusually long legal-name derivatives on one title line when possible."""
    length = len(re.sub(r"\s+", "", _short_company_name(company_name)))
    if length <= 10:
        return 26.0
    if length <= 16:
        return 23.0
    return 20.5


def _cover_metadata_size(value: str) -> float:
    compact_length = len(re.sub(r"\s+", "", value))
    if compact_length <= 22:
        return 9.5
    if compact_length <= 30:
        return 9.0
    return 8.5


def _configure_customer_first_page(section) -> None:
    section.different_first_page_header_footer = True
    for story in (section.first_page_header, section.first_page_footer):
        paragraph = story.paragraphs[0]
        paragraph.text = ""
        properties = paragraph._p.get_or_add_pPr()
        borders = properties.find(qn("w:pBdr"))
        if borders is not None:
            properties.remove(borders)


def _set_cover_metadata_cell(cell, text: str, *, label: bool) -> None:
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
    _shade(cell, PALE_GRAY)
    _set_cell_margins(cell, top=55, start=150, bottom=55, end=150)
    paragraph = cell.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(0)
    paragraph.paragraph_format.line_spacing = 1.0
    run = paragraph.add_run(text)
    run.font.color.rgb = RGBColor(64, 74, 88) if label else BODY_COLOR
    _set_run_font(run, size=9.5 if label else _cover_metadata_size(text), bold=label)


def _add_customer_report_head(
    document: Document,
    company_name: str,
    report: Report,
    *,
    internal_marker: str | None = None,
) -> None:
    """Named first-page override: approved_reference_editorial_cover.

    The existing report body keeps the standard_business_brief contract; this
    explicit A4 cover override follows the editorial_cover hierarchy only.
    """
    if internal_marker:
        marker = document.add_paragraph()
        marker.paragraph_format.space_before = Pt(0)
        marker.paragraph_format.space_after = Pt(0)
        marker_run = marker.add_run(internal_marker)
        marker_run.font.color.rgb = MUTED_COLOR
        _set_run_font(marker_run, size=8.5, bold=True)

    spacer = document.add_paragraph()
    spacer.paragraph_format.space_before = Pt(0)
    spacer.paragraph_format.space_after = Pt(58 if internal_marker else 70)
    spacer.paragraph_format.line_spacing = 1.0

    company = document.add_paragraph()
    company.alignment = WD_ALIGN_PARAGRAPH.CENTER
    company.paragraph_format.space_before = Pt(0)
    company.paragraph_format.space_after = Pt(46)
    run = company.add_run(company_name)
    run.font.color.rgb = RGBColor(96, 106, 120)
    _set_run_font(run, size=10.5, bold=False)

    title_first = document.add_paragraph()
    title_first.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_first.paragraph_format.space_before = Pt(0)
    title_first.paragraph_format.space_after = Pt(2)
    title_first.paragraph_format.line_spacing = 1.0
    run = title_first.add_run(f"{_short_company_name(company_name)} AI 原生转型")
    run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(run, size=_cover_title_size(company_name), bold=True)

    title_second = document.add_paragraph()
    title_second.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_second.paragraph_format.space_before = Pt(0)
    title_second.paragraph_format.space_after = Pt(22)
    title_second.paragraph_format.line_spacing = 1.0
    run = title_second.add_run("诊断报告")
    run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(run, size=25.5, bold=True)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.paragraph_format.space_before = Pt(0)
    subtitle.paragraph_format.space_after = Pt(38)
    subtitle.paragraph_format.line_spacing = 1.0
    run = subtitle.add_run("从诊断共识走向可执行的 AI 转型路径")
    run.font.color.rgb = RGBColor.from_string(RED)
    _set_run_font(run, size=12.5, bold=False)

    rule = document.add_paragraph()
    rule.paragraph_format.left_indent = Cm((REPORT_CONTENT_WIDTH_CM - CUSTOMER_COVER_RULE_WIDTH_CM) / 2)
    rule.paragraph_format.right_indent = Cm((REPORT_CONTENT_WIDTH_CM - CUSTOMER_COVER_RULE_WIDTH_CM) / 2)
    rule.paragraph_format.space_before = Pt(0)
    rule.paragraph_format.space_after = Pt(20)
    rule.paragraph_format.line_spacing = 1.0
    _set_paragraph_border(rule, side="bottom", size=7, space=0)

    metadata = (
        ("评估对象", company_name),
        ("报告类型", "AI 原生企业转型诊断报告"),
        ("评估范围", "企业 AI 原生能力成熟度与转型路径"),
        ("报告编号", _report_number(report)),
        ("出具日期", _report_date(report)),
    )
    meta = document.add_table(rows=0, cols=2)
    meta.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta.autofit = False
    _set_fixed_table_layout(meta)
    _set_table_width(meta, CUSTOMER_COVER_META_WIDTH_CM)
    _set_table_grid_widths(
        meta,
        [CUSTOMER_COVER_META_LABEL_WIDTH_CM, CUSTOMER_COVER_META_VALUE_WIDTH_CM],
    )
    _remove_table_borders(meta)
    for label, value in metadata:
        cells = meta.add_row().cells
        _set_cover_metadata_cell(cells[0], label, label=True)
        _set_cover_metadata_cell(cells[1], value, label=False)
        _set_cell_width(cells[0], CUSTOMER_COVER_META_LABEL_WIDTH_CM)
        _set_cell_width(cells[1], CUSTOMER_COVER_META_VALUE_WIDTH_CM)
        _prevent_row_split(meta.rows[-1])

    footer = document.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.paragraph_format.space_before = Pt(26)
    footer.paragraph_format.space_after = Pt(0)
    footer.paragraph_format.line_spacing = 1.0
    run = footer.add_run("让 AI 从局部工具走向企业级生产力")
    run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(run, size=10.5, bold=True)


def _add_customer_report_score(document: Document, score: CustomerReportScore) -> None:
    heading = document.add_paragraph()
    heading.paragraph_format.space_before = Pt(0)
    heading.paragraph_format.space_after = Pt(5)
    heading.paragraph_format.keep_with_next = True
    run = heading.add_run("诊断结果概览")
    run.font.color.rgb = RGBColor.from_string(NAVY)
    _set_run_font(run, size=13, bold=True)
    _set_paragraph_border(heading, side="left", size=18, space=6)

    score_table = document.add_table(rows=1, cols=2)
    score_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    score_table.autofit = False
    _set_fixed_table_layout(score_table)
    _set_table_width(score_table, REPORT_CONTENT_WIDTH_CM)
    _remove_table_borders(score_table)
    widths = [REPORT_CONTENT_WIDTH_CM / 2] * 2
    _set_table_grid_widths(score_table, widths)
    score_cells = score_table.rows[0].cells
    _set_score_cell(
        score_cells[0],
        "诊断得分",
        f"{_score_number_text(score.total_score)} / {_score_number_text(score.max_score)}",
    )
    _set_score_cell(score_cells[1], "综合得分率", _score_rate_text(score))
    for cell, width in zip(score_cells, widths):
        _set_cell_width(cell, width)
    score_table.rows[0].height = Pt(30)
    score_table.rows[0].height_rule = WD_ROW_HEIGHT_RULE.AT_LEAST
    _prevent_row_split(score_table.rows[-1])

    progress = document.add_table(rows=1, cols=2)
    progress.alignment = WD_TABLE_ALIGNMENT.CENTER
    progress.autofit = False
    _set_fixed_table_layout(progress)
    _set_table_width(progress, REPORT_CONTENT_WIDTH_CM)
    _remove_table_borders(progress)
    completed = max(0.0, min(1.0, score.score_rate)) * REPORT_CONTENT_WIDTH_CM
    progress_widths = [completed, REPORT_CONTENT_WIDTH_CM - completed]
    _set_table_grid_widths(progress, progress_widths)
    progress.rows[0].height = Pt(3)
    progress.rows[0].height_rule = WD_ROW_HEIGHT_RULE.EXACTLY
    for index, (cell, width) in enumerate(zip(progress.rows[0].cells, progress_widths)):
        _set_cell_width(cell, max(width, 0.01))
        _set_cell_margins(cell, top=0, start=0, bottom=0, end=0)
        _shade(cell, PROGRESS_BLUE if index == 0 else PROGRESS_GRAY)
        cell.paragraphs[0].paragraph_format.space_after = Pt(0)

    spacer = document.add_paragraph()
    spacer.paragraph_format.space_after = Pt(2)


def generate_customer_report_docx(
    report: Report,
    company_name: str,
    *,
    score: CustomerReportScore | None = None,
) -> bytes:
    """生成只含客户可见内容的报告 DOCX：报告头（公司/编号/日期/评分）+ 最终诊断报告。

    与内部 Word 档案第三部分共用 build_final_diagnosis_report；不包含客户
    基本信息、联系方式、公开情报分析等内部模块。该 DOCX 是客户 PDF 的唯一来源。
    """
    document = Document()
    _set_document_font(document)
    normalized_company = company_name or "企业"
    _configure_section(
        document.sections[0],
        header_text=f"{normalized_company} | AI 原生转型诊断报告",
        footer_date=_report_date(report),
    )
    _configure_customer_first_page(document.sections[0])
    persisted_score = score if score is not None else customer_report_score(report)
    _add_customer_report_head(document, normalized_company, report)
    document.add_page_break()
    _add_customer_report_score(document, persisted_score)
    build_final_diagnosis_report(document, report)
    output = BytesIO()
    document.save(output)
    return output.getvalue()


def _append_customer_report_to_internal_document(
    document: Document,
    company_name: str,
    report: Report,
) -> None:
    """Append the complete customer deliverable as part three of the archive."""

    section = document.add_section(WD_SECTION.NEW_PAGE)
    section.header.is_linked_to_previous = False
    section.footer.is_linked_to_previous = False
    section.first_page_header.is_linked_to_previous = False
    section.first_page_footer.is_linked_to_previous = False
    _configure_section(
        section,
        header_text=f"{company_name} | AI 原生转型诊断报告",
        footer_date=_report_date(report),
    )
    _configure_customer_first_page(section)
    _add_customer_report_head(
        document,
        company_name,
        report,
        internal_marker="三、客户最终诊断报告",
    )
    document.add_page_break()
    _add_customer_report_score(document, customer_report_score(report))
    build_final_diagnosis_report(document, report)


def generate_lead_export_docx(
    lead: CompanyLead,
    submission: DiagnosisSubmission | None,
    report: Report | None,
    source_name: str | None = None,
    *,
    final_report_sent: bool = True,
) -> bytes:
    """Return the three-part internal customer archive as a DOCX file."""
    document = Document()
    _set_document_font(document)
    _configure_section(document.sections[0])
    company_name = _text(lead.company_name, "客户")
    _add_cover(document, company_name)

    _new_part(document, "一、", "基本信息", "以下内容来自客户提交，不包含公开网络推断。")
    profile = [
        ("公司", company_name),
        ("所在城市", _text(getattr(lead, "city", None))),
        ("行业", _text(lead.industry)),
        ("企业规模", _text(lead.company_size)),
        ("年营收", _text(lead.annual_revenue)),
        ("联系人", _text(lead.contact_name)),
        ("职位", _text(lead.position)),
        ("手机号", _text(lead.phone)),
        ("邮箱", _text(lead.email)),
        ("微信", _text(lead.wechat)),
        ("来源", _text(source_name or lead.source_code)),
        ("填写时间", _format_datetime(getattr(lead, "created_at", None))),
    ]
    table = document.add_table(rows=0, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    for index in range(0, len(profile), 2):
        cells = table.add_row().cells
        _set_cell_text(cells[0], *profile[index])
        _set_cell_text(cells[1], *profile[index + 1])
        _prevent_row_split(table.rows[-1])

    _add_section_title(document, 1, "AI 转型关注点")
    focus = document.add_paragraph(_text(lead.ai_focus or lead.demand_summary, "暂未填写"))
    focus.paragraph_format.line_spacing = 1.3
    _set_paragraph_font(focus)

    _add_section_title(document, 2, "问卷诊断概览")
    if not submission:
        paragraph = document.add_paragraph("客户尚未完成诊断问卷。")
        _set_paragraph_font(paragraph)
    else:
        overview = [
            ("线索等级", _text(lead.lead_level, "LOW").upper()),
            ("综合得分", f"{submission.total_score if submission.total_score is not None else '-'} / {submission.max_score}"),
            ("得分率", f"{round((submission.score_rate or 0) * 100)}%" if submission.score_rate is not None else "未评估"),
            ("问卷完成时间", _format_datetime(submission.submitted_at)),
        ]
        result_table = document.add_table(rows=0, cols=2)
        result_table.style = "Table Grid"
        for index in range(0, len(overview), 2):
            cells = result_table.add_row().cells
            _set_cell_text(cells[0], *overview[index])
            _set_cell_text(cells[1], *overview[index + 1])
            _prevent_row_split(result_table.rows[-1])

    _new_part(
        document,
        "二、",
        "企业公开信息与 AI 情报分析",
        "事实内容来自公开网络信息；挑战、AI 机会和综合分析属于 AI 分析判断。",
    )
    _add_research_section(document, _load_research(report))

    if report and final_report_sent and report.html_content:
        _append_customer_report_to_internal_document(document, company_name, report)
    else:
        _new_part(
            document,
            "三、",
            "客户最终诊断报告",
            "以下内容直接取自已发送给客户的最终报告快照，本次导出不重新生成。",
        )
        _add_final_report(document, report, final_report_sent)

    output = BytesIO()
    document.save(output)
    return output.getvalue()
