"""Generate a structured Word archive for one customer lead."""

from __future__ import annotations

import json
import math
import re
from datetime import datetime
from html.parser import HTMLParser
from io import BytesIO
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor
from PIL import Image, ImageDraw, ImageFont

from app.models import CompanyLead, DiagnosisSubmission, Report
from app.service.company_research import research_section_text, research_subsections
from app.service.report_content import sanitize_report_content
from app.utils.time_utils import to_china_time, utc_now


FONT_NAME = "Microsoft YaHei"
NAVY = "17365D"
PALE_GRAY = "F5F7FA"
BODY_COLOR = RGBColor(31, 44, 61)
MUTED_COLOR = RGBColor(92, 108, 132)
MISSING_RESEARCH = "暂未检索到可靠公开信息"
REPORT_CONTENT_WIDTH_CM = 17.4

RESEARCH_SECTIONS: tuple[tuple[str, str, bool], ...] = (
    ("company_overview", "公司介绍", True),
    ("revenue_scale", "营收规模", True),
    ("products", "产品与服务", True),
    ("industry_characteristics", "行业特点", True),
    ("development_status", "发展现状", True),
    ("challenges", "可能遇到的挑战", False),
    ("ai_opportunities", "AI 能提供的帮助", False),
    ("analysis", "AI 综合分析", False),
)


class _HtmlNode:
    def __init__(self, tag: str, attrs: dict[str, str] | None = None) -> None:
        self.tag = tag
        self.attrs = attrs or {}
        self.children: list[_HtmlNode | str] = []


class _ReportHtmlParser(HTMLParser):
    """Build a small DOM for the controlled report HTML generated by this app."""

    _void_tags = {"br", "hr", "img", "meta", "link", "input"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = _HtmlNode("root")
        self.stack = [self.root]

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        node = _HtmlNode(tag.lower(), {key: value or "" for key, value in attrs})
        self.stack[-1].children.append(node)
        if tag.lower() not in self._void_tags:
            self.stack.append(node)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        for index in range(len(self.stack) - 1, 0, -1):
            if self.stack[index].tag == tag:
                del self.stack[index:]
                break

    def handle_data(self, data: str) -> None:
        if data:
            self.stack[-1].children.append(data)


def _set_run_font(run, size: float | None = None, bold: bool | None = None) -> None:
    run.font.name = FONT_NAME
    if size is not None:
        run.font.size = Pt(size)
    if bold is not None:
        run.bold = bold
    rpr = run._element.get_or_add_rPr()
    rfonts = rpr.rFonts
    if rfonts is None:
        rfonts = OxmlElement("w:rFonts")
        rpr.insert(0, rfonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        rfonts.set(qn(f"w:{attribute}"), FONT_NAME)


def _set_paragraph_font(paragraph, size: float = 10.5) -> None:
    for run in paragraph.runs:
        _set_run_font(run, size=size)


def _set_document_font(document: Document) -> None:
    for style in document.styles:
        if not getattr(style, "font", None):
            continue
        style.font.name = FONT_NAME
        style.font.color.rgb = BODY_COLOR
        rpr = style._element.get_or_add_rPr()
        rfonts = rpr.rFonts
        if rfonts is None:
            rfonts = OxmlElement("w:rFonts")
            rpr.insert(0, rfonts)
        for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
            rfonts.set(qn(f"w:{attribute}"), FONT_NAME)
    document.styles["Normal"].font.size = Pt(10.5)


def _text(value: object | None, fallback: str = "未填写") -> str:
    if value is None or str(value).strip() == "":
        return fallback
    return str(value).strip()


def _format_datetime(value: datetime | None, fallback: str = "未记录") -> str:
    if value is None:
        return fallback
    return to_china_time(value).strftime("%Y-%m-%d %H:%M:%S")


def _shade(cell, color: str) -> None:
    properties = cell._tc.get_or_add_tcPr()
    shading = properties.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        properties.append(shading)
    shading.set(qn("w:fill"), color)


def _set_cell_margins(cell, top: int = 90, start: int = 110, bottom: int = 90, end: int = 110) -> None:
    properties = cell._tc.get_or_add_tcPr()
    margins = properties.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        properties.append(margins)
    for side, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        element = margins.find(qn(f"w:{side}"))
        if element is None:
            element = OxmlElement(f"w:{side}")
            margins.append(element)
        element.set(qn("w:w"), str(value))
        element.set(qn("w:type"), "dxa")


def _prevent_row_split(row) -> None:
    properties = row._tr.get_or_add_trPr()
    if properties.find(qn("w:cantSplit")) is None:
        properties.append(OxmlElement("w:cantSplit"))


def _repeat_table_header(row) -> None:
    properties = row._tr.get_or_add_trPr()
    if properties.find(qn("w:tblHeader")) is None:
        properties.append(OxmlElement("w:tblHeader"))


def _set_fixed_table_layout(table) -> None:
    properties = table._tbl.tblPr
    layout = properties.find(qn("w:tblLayout"))
    if layout is None:
        layout = OxmlElement("w:tblLayout")
        properties.append(layout)
    layout.set(qn("w:type"), "fixed")


def _set_table_grid_widths(table, widths_cm: list[float]) -> None:
    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width_cm in widths_cm:
        column = OxmlElement("w:gridCol")
        column.set(qn("w:w"), str(Cm(width_cm).twips))
        grid.append(column)


def _set_cell_width(cell, width_cm: float) -> None:
    cell.width = Cm(width_cm)
    properties = cell._tc.get_or_add_tcPr()
    width = properties.find(qn("w:tcW"))
    if width is None:
        width = OxmlElement("w:tcW")
        properties.append(width)
    width.set(qn("w:w"), str(Cm(width_cm).twips))
    width.set(qn("w:type"), "dxa")


def _set_cell_text(cell, label: str, value: str) -> None:
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
    _shade(cell, PALE_GRAY)
    _set_cell_margins(cell)
    paragraph = cell.paragraphs[0]
    paragraph.paragraph_format.space_after = Pt(0)
    label_run = paragraph.add_run(f"{label}\n")
    label_run.font.color.rgb = MUTED_COLOR
    _set_run_font(label_run, size=8.5, bold=True)
    value_run = paragraph.add_run(value)
    value_run.font.color.rgb = BODY_COLOR
    _set_run_font(value_run, size=10.5, bold=True)


def _add_part_title(document: Document, number: str, title: str, subtitle: str | None = None) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(7)
    paragraph.paragraph_format.keep_with_next = True
    title_run = paragraph.add_run(f"{number}{title}")
    title_run.font.color.rgb = RGBColor(18, 46, 77)
    _set_run_font(title_run, size=19, bold=True)
    if subtitle:
        note = document.add_paragraph(subtitle)
        note.paragraph_format.space_after = Pt(14)
        for run in note.runs:
            run.font.color.rgb = MUTED_COLOR
            _set_run_font(run, size=9.5)


def _add_section_title(document: Document, number: int | str, title: str) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(13)
    paragraph.paragraph_format.space_after = Pt(6)
    paragraph.paragraph_format.keep_with_next = True
    run = paragraph.add_run(f"{number}. {title}")
    run.font.color.rgb = RGBColor(20, 76, 112)
    _set_run_font(run, size=13, bold=True)


def _add_page_number(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = " PAGE "
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend([begin, instruction, end])
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=8.5)


def _configure_section(section, header_text: str = "AI 原生企业转型诊断档案") -> None:
    section.top_margin = Cm(1.8)
    section.bottom_margin = Cm(1.7)
    section.left_margin = Cm(1.8)
    section.right_margin = Cm(1.8)
    section.header_distance = Cm(0.7)
    section.footer_distance = Cm(0.7)
    header = section.header.paragraphs[0]
    header.text = header_text
    header.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in header.runs:
        run.font.color.rgb = MUTED_COLOR
        _set_run_font(run, size=8)
    _add_page_number(section.footer.paragraphs[0])


def _add_cover(document: Document, company_name: str) -> None:
    for _ in range(4):
        document.add_paragraph()
    eyebrow = document.add_paragraph()
    eyebrow.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = eyebrow.add_run("后台客户诊断档案")
    run.font.color.rgb = RGBColor(47, 102, 157)
    _set_run_font(run, size=11, bold=True)
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_before = Pt(10)
    title.paragraph_format.space_after = Pt(16)
    run = title.add_run(company_name)
    run.font.color.rgb = RGBColor(13, 48, 82)
    _set_run_font(run, size=25, bold=True)
    subject = document.add_paragraph()
    subject.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subject.add_run("AI 转型诊断完整档案")
    run.font.color.rgb = RGBColor(33, 74, 117)
    _set_run_font(run, size=18, bold=True)
    generated = document.add_paragraph()
    generated.alignment = WD_ALIGN_PARAGRAPH.CENTER
    generated.paragraph_format.space_before = Pt(34)
    run = generated.add_run(f"导出时间：{_format_datetime(utc_now())}（北京时间）")
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=9.5)
    confidentiality = document.add_paragraph()
    confidentiality.alignment = WD_ALIGN_PARAGRAPH.CENTER
    confidentiality.paragraph_format.space_before = Pt(120)
    run = confidentiality.add_run("内部资料 · 请妥善保管")
    run.font.color.rgb = MUTED_COLOR
    _set_run_font(run, size=9)


def _new_part(document: Document, number: str, title: str, subtitle: str | None = None) -> None:
    document.add_page_break()
    _add_part_title(document, number, title, subtitle)


def _load_research(report: Report | None) -> dict:
    if not report or not report.company_research_json:
        return {}
    try:
        value = json.loads(report.company_research_json)
        return value if isinstance(value, dict) else {}
    except (TypeError, json.JSONDecodeError):
        return {}


def _source_reference_text(research: dict, key: str, source_count: int) -> str:
    references = research.get("source_refs") or {}
    values = references.get(key) if isinstance(references, dict) else None
    if isinstance(values, list):
        indexes = [int(value) for value in values if str(value).isdigit() and 1 <= int(value) <= source_count]
        if indexes:
            return "资料来源：" + " ".join(f"[来源{index}]" for index in dict.fromkeys(indexes))
    if research.get(key) == MISSING_RESEARCH:
        return "资料来源：暂未检索到可靠公开信息"
    return "资料来源：证据校验失败，未找到可核验来源编号"


def _add_research_section(document: Document, research: dict) -> None:
    sources = [item for item in (research.get("sources") or []) if isinstance(item, dict)]
    for index, (key, title, factual) in enumerate(RESEARCH_SECTIONS, start=1):
        _add_section_title(document, index, title)
        value = research.get(key)
        subsections = research_subsections(value)
        if subsections:
            for subsection in subsections:
                heading = document.add_paragraph()
                heading.paragraph_format.space_before = Pt(2)
                heading.paragraph_format.space_after = Pt(2)
                run = heading.add_run(subsection["title"])
                run.bold = True
                run.font.color.rgb = RGBColor.from_string(NAVY)
                _set_run_font(run, size=10.5)
                paragraph = document.add_paragraph(subsection["content"])
                paragraph.paragraph_format.line_spacing = 1.35
                paragraph.paragraph_format.space_after = Pt(5)
                _set_paragraph_font(paragraph)
        else:
            content = research_section_text(value) or MISSING_RESEARCH
            paragraph = document.add_paragraph(content)
            paragraph.paragraph_format.line_spacing = 1.35
            paragraph.paragraph_format.space_after = Pt(5)
            _set_paragraph_font(paragraph)
        if factual:
            source_note = document.add_paragraph(_source_reference_text(research, key, len(sources)))
            source_note.paragraph_format.space_after = Pt(8)
            for run in source_note.runs:
                run.font.color.rgb = MUTED_COLOR
                _set_run_font(run, size=8.5)
        else:
            analysis_note = document.add_paragraph("性质说明：结合公开信息形成的 AI 分析判断，不作为已核实事实。")
            analysis_note.paragraph_format.space_after = Pt(8)
            for run in analysis_note.runs:
                run.font.color.rgb = MUTED_COLOR
                _set_run_font(run, size=8.5)

    _add_section_title(document, 9, "信息来源")
    researched_at = _text(research.get("researched_at"), "未记录")
    note = document.add_paragraph(f"检索时间：{researched_at}")
    for run in note.runs:
        run.font.color.rgb = MUTED_COLOR
        _set_run_font(run, size=8.5)
    if not sources:
        paragraph = document.add_paragraph(MISSING_RESEARCH)
        _set_paragraph_font(paragraph)
        return
    table = document.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    headers = ("编号", "来源", "网址")
    for cell, header in zip(table.rows[0].cells, headers):
        _shade(cell, NAVY)
        cell.text = header
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in paragraph.runs:
                run.font.color.rgb = RGBColor(255, 255, 255)
                _set_run_font(run, size=9, bold=True)
    for index, source in enumerate(sources, start=1):
        cells = table.add_row().cells
        values = (f"来源{index}", _text(source.get("title"), "未命名来源"), _text(source.get("url"), "未提供网址"))
        for cell, value in zip(cells, values):
            _set_cell_margins(cell)
            cell.text = value
            for paragraph in cell.paragraphs:
                _set_paragraph_font(paragraph, size=8.5)
        if index % 2 == 0:
            for cell in cells:
                _shade(cell, PALE_GRAY)
        _prevent_row_split(table.rows[-1])


def _node_text(node: _HtmlNode | str) -> str:
    if isinstance(node, str):
        return node
    if node.tag == "br":
        return "\n"
    return "".join(_node_text(child) for child in node.children)


def _normalized_node_text(node: _HtmlNode | str) -> str:
    value = _node_text(node).replace("\xa0", " ")
    lines = [re.sub(r"[ \t]+", " ", line).strip() for line in value.splitlines()]
    return "\n".join(line for line in lines if line).strip()


def _load_report_dimensions(report: Report | None) -> list[dict]:
    if not report or not getattr(report, "summary_json", None):
        return []
    try:
        payload = json.loads(report.summary_json)
    except (TypeError, json.JSONDecodeError):
        return []
    dimensions = payload.get("dimensions") if isinstance(payload, dict) else None
    if not isinstance(dimensions, list):
        return []
    return [item for item in dimensions if isinstance(item, dict) and item.get("module_name")]


def _chart_font(size: int, *, bold: bool = False):
    candidates = (
        Path("C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJKsc-Bold.otf" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJKsc-Regular.otf"),
        Path("/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"),
    )
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size=size)
    return ImageFont.load_default()


def _dimension_rate(dimension: dict) -> float:
    try:
        return max(0.0, min(1.0, float(dimension.get("score_rate") or 0)))
    except (TypeError, ValueError):
        return 0.0


def _fit_label(draw: ImageDraw.ImageDraw, value: str, font, max_width: int) -> str:
    if draw.textbbox((0, 0), value, font=font)[2] <= max_width:
        return value
    suffix = "..."
    trimmed = value
    while trimmed and draw.textbbox((0, 0), trimmed + suffix, font=font)[2] > max_width:
        trimmed = trimmed[:-1]
    return trimmed + suffix


def _draw_chart_heading(draw: ImageDraw.ImageDraw, title: str, subtitle: str) -> None:
    draw.text((46, 28), title, fill="#182942", font=_chart_font(34, bold=True))
    draw.text((46, 76), subtitle, fill="#8190A6", font=_chart_font(21))


def _build_ranking_chart(dimensions: list[dict]) -> BytesIO:
    ordered = sorted(dimensions, key=_dimension_rate)
    row_height = 54
    height = max(410, 160 + len(ordered) * row_height)
    image = Image.new("RGB", (1400, height), "white")
    draw = ImageDraw.Draw(image)
    _draw_chart_heading(draw, "能力成熟度排行", "当前启用维度得分率从低到高排列，快速定位优先改善环节")
    left, right, top = 370, 1320, 140
    chart_width = right - left
    label_font = _chart_font(23)
    value_font = _chart_font(21, bold=True)
    for tick in range(0, 101, 25):
        x = left + chart_width * tick / 100
        draw.line((x, top, x, height - 55), fill="#E2E8F0", width=2)
        label = f"{tick}%"
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((x - (box[2] - box[0]) / 2, height - 44), label, fill="#8A98AA", font=label_font)
    for index, dimension in enumerate(ordered):
        rate = _dimension_rate(dimension)
        y = top + index * row_height + 8
        label = _fit_label(draw, str(dimension.get("module_name") or ""), label_font, 285)
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((left - 28 - (box[2] - box[0]), y + 4), label, fill="#58677D", font=label_font)
        bar_width = max(4, int(chart_width * rate))
        fill = "#FFF1DD" if rate < 0.5 else "#DCE9FF"
        outline = "#F59E0B" if rate < 0.5 else "#3978E6"
        draw.rounded_rectangle((left, y, left + bar_width, y + 30), radius=7, fill=fill, outline=outline, width=3)
        draw.text((min(left + bar_width + 14, right - 58), y + 2), f"{round(rate * 100)}%", fill="#34445B", font=value_font)
    output = BytesIO()
    image.save(output, format="PNG", optimize=True)
    output.seek(0)
    return output


def _build_radar_chart(dimensions: list[dict]) -> BytesIO:
    count = len(dimensions)
    size = 1040
    image = Image.new("RGB", (1400, size), "white")
    draw = ImageDraw.Draw(image)
    _draw_chart_heading(draw, "AI 转型能力雷达图", "面积越大代表各项能力越均衡，橙色节点标记得分率低于 50% 的维度")
    center_x, center_y = 700, 565
    radius = 330
    angles = [(-math.pi / 2) + 2 * math.pi * index / count for index in range(count)]
    for level in (0.25, 0.5, 0.75, 1.0):
        points = [(center_x + radius * level * math.cos(angle), center_y + radius * level * math.sin(angle)) for angle in angles]
        draw.polygon(points, outline="#D9E3EF", width=2)
    for angle in angles:
        draw.line((center_x, center_y, center_x + radius * math.cos(angle), center_y + radius * math.sin(angle)), fill="#D9E3EF", width=2)
    values = [_dimension_rate(dimension) for dimension in dimensions]
    points = [(center_x + radius * rate * math.cos(angle), center_y + radius * rate * math.sin(angle)) for rate, angle in zip(values, angles)]
    overlay = Image.new("RGBA", image.size, (255, 255, 255, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    overlay_draw.polygon(points, fill=(126, 171, 244, 70), outline="#3278E8", width=6)
    image = Image.alpha_composite(image.convert("RGBA"), overlay)
    draw = ImageDraw.Draw(image)
    for (x, y), rate in zip(points, values):
        color = "#F59E0B" if rate < 0.5 else "#3278E8"
        draw.ellipse((x - 11, y - 11, x + 11, y + 11), fill=color, outline="white", width=4)
    label_font = _chart_font(23)
    for dimension, angle in zip(dimensions, angles):
        label = _fit_label(draw, str(dimension.get("module_name") or ""), label_font, 250)
        label_radius = radius + 74
        x = center_x + label_radius * math.cos(angle)
        y = center_y + label_radius * math.sin(angle)
        box = draw.textbbox((0, 0), label, font=label_font)
        draw.text((x - (box[2] - box[0]) / 2, y - (box[3] - box[1]) / 2), label, fill="#47566D", font=label_font)
    output = BytesIO()
    image.convert("RGB").save(output, format="PNG", optimize=True)
    output.seek(0)
    return output


def _add_maturity_charts(document: Document, dimensions: list[dict]) -> None:
    if len(dimensions) < 3:
        return
    for chart in (_build_ranking_chart(dimensions), _build_radar_chart(dimensions)):
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.paragraph_format.space_before = Pt(4)
        paragraph.paragraph_format.space_after = Pt(10)
        paragraph.add_run().add_picture(chart, width=Cm(16.2))


def _add_inline_runs(paragraph, node: _HtmlNode | str, bold: bool = False) -> None:
    if isinstance(node, str):
        text = re.sub(r"[ \t\r\n]+", " ", node)
        if text:
            run = paragraph.add_run(text)
            _set_run_font(run, size=10, bold=bold)
        return
    if node.tag == "br":
        paragraph.add_run().add_break()
        return
    next_bold = bold or node.tag in {"strong", "b"}
    for child in node.children:
        _add_inline_runs(paragraph, child, next_bold)


def _find_descendants(node: _HtmlNode, tags: set[str]) -> list[_HtmlNode]:
    found: list[_HtmlNode] = []
    for child in node.children:
        if not isinstance(child, _HtmlNode):
            continue
        if child.tag in tags:
            found.append(child)
        else:
            found.extend(_find_descendants(child, tags))
    return found


def _add_report_table(document: Document, node: _HtmlNode) -> None:
    rows = _find_descendants(node, {"tr"})
    parsed_rows: list[tuple[list[str], bool]] = []
    for row in rows:
        cells = [child for child in row.children if isinstance(child, _HtmlNode) and child.tag in {"th", "td"}]
        if not cells:
            cells = _find_descendants(row, {"th", "td"})
        if cells:
            parsed_rows.append(([_normalized_node_text(cell) for cell in cells], any(cell.tag == "th" for cell in cells)))
    if not parsed_rows:
        return
    column_count = max(len(row) for row, _ in parsed_rows)
    table = document.add_table(rows=0, cols=column_count)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    _set_fixed_table_layout(table)
    classes = set(node.attrs.get("class", "").split())
    is_summary_table = "report-finding-table" in classes and not classes.intersection(
        {"report-cad-table", "report-contradiction-table", "report-workshop-table"}
    )
    if "report-workshop-table" in classes and column_count == 5:
        ratios = (0.09, 0.20, 0.29, 0.28, 0.14)
    elif "report-cad-table" in classes and column_count == 3:
        ratios = (0.12, 0.40, 0.48)
    elif "report-contradiction-table" in classes and column_count == 3:
        ratios = (0.29, 0.31, 0.40)
    elif is_summary_table and column_count == 3:
        ratios = (0.07, 0.30, 0.63)
    else:
        ratios = tuple(1 / column_count for _ in range(column_count))
    widths = [REPORT_CONTENT_WIDTH_CM * ratio for ratio in ratios]
    _set_table_grid_widths(table, widths)
    for row_index, (values, is_header) in enumerate(parsed_rows):
        cells = table.add_row().cells
        for cell_index, cell in enumerate(cells):
            value = values[cell_index] if cell_index < len(values) else ""
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.TOP
            _set_cell_width(cell, widths[cell_index])
            horizontal_margin = 35 if is_summary_table and cell_index == 0 else 100
            _set_cell_margins(cell, top=90, start=horizontal_margin, bottom=90, end=horizontal_margin)
            cell.text = value
            if is_header:
                _shade(cell, NAVY)
            elif row_index % 2 == 0:
                _shade(cell, PALE_GRAY)
            for paragraph in cell.paragraphs:
                paragraph.paragraph_format.space_after = Pt(0)
                paragraph.paragraph_format.line_spacing = 1.15
                if cell_index == 0 and is_summary_table:
                    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in paragraph.runs:
                    run.font.color.rgb = RGBColor(255, 255, 255) if is_header else BODY_COLOR
                    font_size = 8 if column_count >= 4 or (is_summary_table and cell_index == 0) else 9
                    _set_run_font(run, size=font_size, bold=is_header or (cell_index == 1 and is_summary_table))
        if is_header:
            _repeat_table_header(table.rows[-1])
            _prevent_row_split(table.rows[-1])
    if "report-cad-table" in classes and len(table.rows) > 2:
        core_conclusion = parsed_rows[1][0][0] if parsed_rows[1][0] else ""
        merged_cell = table.cell(1, 0).merge(table.cell(len(table.rows) - 1, 0))
        merged_cell.text = core_conclusion
        merged_cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        _set_cell_margins(merged_cell, top=110, start=110, bottom=110, end=110)
        for paragraph in merged_cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            paragraph.paragraph_format.space_after = Pt(0)
            paragraph.paragraph_format.line_spacing = 1.2
            for run in paragraph.runs:
                run.font.color.rgb = BODY_COLOR
                _set_run_font(run, size=9, bold=True)
    document.add_paragraph().paragraph_format.space_after = Pt(0)


def _render_report_nodes(
    document: Document,
    nodes: Iterable[_HtmlNode | str],
    dimensions: list[dict] | None = None,
    chart_state: dict[str, bool] | None = None,
) -> None:
    chart_state = chart_state if chart_state is not None else {"inserted": False}
    for node in nodes:
        if isinstance(node, str):
            if node.strip():
                paragraph = document.add_paragraph(node.strip())
                _set_paragraph_font(paragraph)
            continue
        classes = set(node.attrs.get("class", "").split())
        if node.tag == "h2":
            heading_text = _normalized_node_text(node)
            paragraph = document.add_paragraph()
            paragraph.paragraph_format.space_before = Pt(14)
            paragraph.paragraph_format.space_after = Pt(7)
            paragraph.paragraph_format.keep_with_next = True
            run = paragraph.add_run(heading_text)
            run.font.color.rgb = RGBColor(20, 76, 112)
            _set_run_font(run, size=15, bold=True)
            if heading_text.startswith("二、能力成熟度") and dimensions and not chart_state["inserted"]:
                _add_maturity_charts(document, dimensions)
                chart_state["inserted"] = True
        elif node.tag in {"h3", "h4"} or "report-module-head" in classes:
            paragraph = document.add_paragraph()
            paragraph.paragraph_format.space_before = Pt(9)
            paragraph.paragraph_format.space_after = Pt(5)
            paragraph.paragraph_format.keep_with_next = True
            run = paragraph.add_run(_normalized_node_text(node))
            run.font.color.rgb = RGBColor(33, 74, 117)
            _set_run_font(run, size=11.5, bold=True)
        elif node.tag == "p" or "report-module-body" in classes:
            paragraph = document.add_paragraph()
            paragraph.paragraph_format.line_spacing = 1.25
            paragraph.paragraph_format.space_after = Pt(5)
            for child in node.children:
                _add_inline_runs(paragraph, child)
        elif node.tag == "table":
            _add_report_table(document, node)
        elif node.tag in {"ol", "ul"}:
            list_style = "List Number" if node.tag == "ol" else "List Bullet"
            for item in [child for child in node.children if isinstance(child, _HtmlNode) and child.tag == "li"]:
                paragraph = document.add_paragraph(style=list_style)
                paragraph.paragraph_format.space_after = Pt(5)
                for child in item.children:
                    _add_inline_runs(paragraph, child)
        elif node.tag in {"article", "section", "div", "main", "body", "root"}:
            _render_report_nodes(document, node.children, dimensions, chart_state)


def _add_final_report(document: Document, report: Report | None, final_report_sent: bool) -> None:
    if not report or not final_report_sent or not report.html_content:
        paragraph = document.add_paragraph("客户最终诊断报告尚未发送，暂无可导出的最终版本。")
        paragraph.paragraph_format.space_before = Pt(12)
        _set_paragraph_font(paragraph)
        return
    parser = _ReportHtmlParser()
    parser.feed(sanitize_report_content(report.html_content))
    _render_report_nodes(document, parser.root.children, _load_report_dimensions(report))


def generate_lead_export_docx(
    lead: CompanyLead,
    submission: DiagnosisSubmission | None,
    report: Report | None,
    source_name: str | None = None,
    *,
    final_report_sent: bool = True,
) -> bytes:
    """Return the three-part internal customer archive as a DOCX file."""
    document = Document()
    _set_document_font(document)
    _configure_section(document.sections[0])
    company_name = _text(lead.company_name, "客户")
    _add_cover(document, company_name)

    _new_part(document, "一、", "基本信息", "以下内容来自客户提交，不包含公开网络推断。")
    profile = [
        ("公司", company_name),
        ("所在城市", _text(getattr(lead, "city", None))),
        ("行业", _text(lead.industry)),
        ("企业规模", _text(lead.company_size)),
        ("年营收", _text(lead.annual_revenue)),
        ("联系人", _text(lead.contact_name)),
        ("职位", _text(lead.position)),
        ("手机号", _text(lead.phone)),
        ("邮箱", _text(lead.email)),
        ("微信", _text(lead.wechat)),
        ("来源", _text(source_name or lead.source_code)),
        ("填写时间", _format_datetime(getattr(lead, "created_at", None))),
    ]
    table = document.add_table(rows=0, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    for index in range(0, len(profile), 2):
        cells = table.add_row().cells
        _set_cell_text(cells[0], *profile[index])
        _set_cell_text(cells[1], *profile[index + 1])
        _prevent_row_split(table.rows[-1])

    _add_section_title(document, 1, "AI 转型关注点")
    focus = document.add_paragraph(_text(lead.ai_focus or lead.demand_summary, "暂未填写"))
    focus.paragraph_format.line_spacing = 1.3
    _set_paragraph_font(focus)

    _add_section_title(document, 2, "问卷诊断概览")
    if not submission:
        paragraph = document.add_paragraph("客户尚未完成诊断问卷。")
        _set_paragraph_font(paragraph)
    else:
        overview = [
            ("线索等级", _text(lead.lead_level, "LOW").upper()),
            ("综合得分", f"{submission.total_score if submission.total_score is not None else '-'} / {submission.max_score}"),
            ("得分率", f"{round((submission.score_rate or 0) * 100)}%" if submission.score_rate is not None else "未评估"),
            ("问卷完成时间", _format_datetime(submission.submitted_at)),
        ]
        result_table = document.add_table(rows=0, cols=2)
        result_table.style = "Table Grid"
        for index in range(0, len(overview), 2):
            cells = result_table.add_row().cells
            _set_cell_text(cells[0], *overview[index])
            _set_cell_text(cells[1], *overview[index + 1])
            _prevent_row_split(result_table.rows[-1])

    _new_part(
        document,
        "二、",
        "企业公开信息与 AI 情报分析",
        "事实内容来自公开网络信息；挑战、AI 机会和综合分析属于 AI 分析判断。",
    )
    _add_research_section(document, _load_research(report))

    _new_part(
        document,
        "三、",
        "客户最终诊断报告",
        "以下内容直接取自已发送给客户的最终报告快照，本次导出不重新生成。",
    )
    _add_final_report(document, report, final_report_sent)

    output = BytesIO()
    document.save(output)
    return output.getvalue()
