"""complete schema baseline before report processing status fields

Revision ID: 2f1c343e7a91
Revises:
Create Date: 2026-07-06 17:08:11.588426
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "2f1c343e7a91"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('function_area', sa.String(length=120), nullable=False),
    sa.Column('module_code', sa.String(length=40), nullable=False),
    sa.Column('maturity', sa.String(length=80), nullable=False),
    sa.Column('roi_level', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_benefit', sa.Text(), nullable=False),
    sa.Column('priority_tag', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_studies_function_area'), 'case_studies', ['function_area'], unique=False)
    op.create_index(op.f('ix_case_studies_industry'), 'case_studies', ['industry'], unique=False)
    op.create_index(op.f('ix_case_studies_module_code'), 'case_studies', ['module_code'], unique=False)
    op.create_table('channel_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_sources_code'), 'channel_sources', ['code'], unique=True)
    op.create_table('company_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('company_size', sa.String(length=80), nullable=True),
    sa.Column('annual_revenue', sa.String(length=80), nullable=True),
    sa.Column('contact_name', sa.String(length=80), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('wechat', sa.String(length=80), nullable=True),
    sa.Column('ai_focus', sa.Text(), nullable=True),
    sa.Column('privacy_accepted', sa.Boolean(), nullable=False),
    sa.Column('contact_authorized', sa.Boolean(), nullable=False),
    sa.Column('source_code', sa.String(length=80), nullable=True),
    sa.Column('lead_level', sa.String(length=40), nullable=False),
    sa.Column('priority_strategy', sa.String(length=40), nullable=True),
    sa.Column('demand_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_leads_company_name'), 'company_leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_leads_created_at'), 'company_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_leads_industry'), 'company_leads', ['industry'], unique=False)
    op.create_index(op.f('ix_company_leads_lead_level'), 'company_leads', ['lead_level'], unique=False)
    op.create_index(op.f('ix_company_leads_priority_strategy'), 'company_leads', ['priority_strategy'], unique=False)
    op.create_index(op.f('ix_company_leads_session_token'), 'company_leads', ['session_token'], unique=True)
    op.create_index(op.f('ix_company_leads_source_code'), 'company_leads', ['source_code'], unique=False)
    op.create_table('gateway_api_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_enabled', sa.Boolean(), nullable=False),
    sa.Column('search_provider', sa.String(length=32), nullable=False),
    sa.Column('search_api_key', sa.String(length=255), nullable=True),
    sa.Column('search_base_url', sa.String(length=500), nullable=True),
    sa.Column('search_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('search_max_results', sa.Integer(), nullable=False),
    sa.Column('search_model', sa.String(length=120), nullable=True),
    sa.Column('llm_api_key', sa.String(length=255), nullable=True),
    sa.Column('llm_base_url', sa.String(length=500), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_modules_code'), 'question_modules', ['code'], unique=True)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('diagnosis_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('score_rate', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['company_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_submissions_lead_id'), 'diagnosis_submissions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_submissions_risk_level'), 'diagnosis_submissions', ['risk_level'], unique=False)
    op.create_table('export_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=80), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_logs_user_id'), 'export_logs', ['user_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=120), nullable=True),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('dimension', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['question_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'code', name='uq_question_module_code')
    )
    op.create_index(op.f('ix_questions_code'), 'questions', ['code'], unique=False)
    op.create_index(op.f('ix_questions_module_id'), 'questions', ['module_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['company_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_created_at'), 'tracking_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_name'), 'tracking_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_tracking_events_lead_id'), 'tracking_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_session_token'), 'tracking_events', ['session_token'], unique=False)
    op.create_table('dimension_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('score_rate', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['question_modules.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['diagnosis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'module_id', name='uq_submission_module_score')
    )
    op.create_index(op.f('ix_dimension_scores_module_id'), 'dimension_scores', ['module_id'], unique=False)
    op.create_index(op.f('ix_dimension_scores_submission_id'), 'dimension_scores', ['submission_id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['diagnosis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_submission_question')
    )
    op.create_index(op.f('ix_question_answers_question_id'), 'question_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_answers_submission_id'), 'question_answers', ['submission_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('company_research_json', sa.Text(), nullable=True),
    sa.Column('research_status', sa.String(length=32), nullable=False),
    sa.Column('research_started_at', sa.DateTime(), nullable=True),
    sa.Column('research_completed_at', sa.DateTime(), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_status', sa.String(length=32), nullable=False),
    sa.Column('pdf_started_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_completed_at', sa.DateTime(), nullable=True),
    sa.Column('model_vendor', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['diagnosis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_public_token'), 'reports', ['public_token'], unique=True)
    op.create_index(op.f('ix_reports_submission_id'), 'reports', ['submission_id'], unique=True)
    op.create_table('ai_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_vendor', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['company_leads.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['diagnosis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_messages_created_at'), 'ai_conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversation_messages_lead_id'), 'ai_conversation_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_messages_purpose'), 'ai_conversation_messages', ['purpose'], unique=False)
    op.create_index(op.f('ix_ai_conversation_messages_report_id'), 'ai_conversation_messages', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_messages_role'), 'ai_conversation_messages', ['role'], unique=False)
    op.create_index(op.f('ix_ai_conversation_messages_submission_id'), 'ai_conversation_messages', ['submission_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_studies.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_case_id'), 'recommendations', ['case_id'], unique=False)
    op.create_index(op.f('ix_recommendations_report_id'), 'recommendations', ['report_id'], unique=False)
    op.create_table('report_delivery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['company_leads.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['diagnosis_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_delivery_jobs_created_at'), 'report_delivery_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_lead_id'), 'report_delivery_jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_recipient_email'), 'report_delivery_jobs', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_report_id'), 'report_delivery_jobs', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_run_after'), 'report_delivery_jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_status'), 'report_delivery_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_report_delivery_jobs_submission_id'), 'report_delivery_jobs', ['submission_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_delivery_jobs_submission_id'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_status'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_run_after'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_report_id'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_recipient_email'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_lead_id'), table_name='report_delivery_jobs')
    op.drop_index(op.f('ix_report_delivery_jobs_created_at'), table_name='report_delivery_jobs')
    op.drop_table('report_delivery_jobs')
    op.drop_index(op.f('ix_recommendations_report_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_case_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ai_conversation_messages_submission_id'), table_name='ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversation_messages_role'), table_name='ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversation_messages_report_id'), table_name='ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversation_messages_purpose'), table_name='ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversation_messages_lead_id'), table_name='ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversation_messages_created_at'), table_name='ai_conversation_messages')
    op.drop_table('ai_conversation_messages')
    op.drop_index(op.f('ix_reports_submission_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_public_token'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_question_answers_submission_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_question_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_dimension_scores_submission_id'), table_name='dimension_scores')
    op.drop_index(op.f('ix_dimension_scores_module_id'), table_name='dimension_scores')
    op.drop_table('dimension_scores')
    op.drop_index(op.f('ix_tracking_events_session_token'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_lead_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_event_name'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_created_at'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_questions_module_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_code'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_export_logs_user_id'), table_name='export_logs')
    op.drop_table('export_logs')
    op.drop_index(op.f('ix_diagnosis_submissions_risk_level'), table_name='diagnosis_submissions')
    op.drop_index(op.f('ix_diagnosis_submissions_lead_id'), table_name='diagnosis_submissions')
    op.drop_table('diagnosis_submissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_question_modules_code'), table_name='question_modules')
    op.drop_table('question_modules')
    op.drop_table('gateway_api_config')
    op.drop_index(op.f('ix_company_leads_source_code'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_session_token'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_priority_strategy'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_lead_level'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_industry'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_created_at'), table_name='company_leads')
    op.drop_index(op.f('ix_company_leads_company_name'), table_name='company_leads')
    op.drop_table('company_leads')
    op.drop_index(op.f('ix_channel_sources_code'), table_name='channel_sources')
    op.drop_table('channel_sources')
    op.drop_index(op.f('ix_case_studies_module_code'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_industry'), table_name='case_studies')
    op.drop_index(op.f('ix_case_studies_function_area'), table_name='case_studies')
    op.drop_table('case_studies')
    # ### end Alembic commands ###
